# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1, verbose_name='Card Count')),
                ('sorting_id', models.CharField(default='Unknown', max_length=100)),
                ('unit_name', models.CharField(max_length=100, verbose_name='Name')),
                ('faction', models.CharField(max_length=25)),
                ('race', models.CharField(max_length=25)),
                ('classification', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('nature', models.CharField(max_length=25)),
                ('size', models.CharField(max_length=25)),
                ('life', models.IntegerField()),
                ('move', models.IntegerField()),
                ('range', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('points', models.IntegerField()),
                ('ability_1', models.TextField(null=True)),
                ('ability_2', models.TextField(null=True)),
                ('ability_3', models.TextField(null=True)),
                ('ability_4', models.TextField(null=True)),
                ('ability_5', models.TextField(null=True)),
            ],
        ),
    ]
