# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heroscape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_image',
            field=models.ImageField(default='None', upload_to=''),
        ),
    ]
