# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heroscape', '0002_card_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
