# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heroscape', '0003_auto_20170516_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='sorting_id',
        ),
        migrations.AddField(
            model_name='card',
            name='ability_1_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='ability_2_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='ability_3_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='ability_4_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='ability_5_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='unit_count',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='ability_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='ability_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='ability_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='ability_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='ability_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=models.ImageField(default='None', upload_to='card_images'),
        ),
    ]
